language: go
go:
- 1.1
- 1.2
- 1.3

env:
  - KAFKA_INSTALL_ROOT=/home/travis/kafka KAFKA_HOSTNAME=localhost

before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- vagrant/install_cluster.sh
- vagrant/boot_cluster.sh
- vagrant/create_topics.sh

notifications:
  flowdock: 15e08f7ed3a8fd2d89ddb36435301c1a
